@TmsApi_HostAddress = http://localhost:5034
@TmsApi_BearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTg4ODQ3ODQwMH0.7s8n9j8v9s8

GET {{TmsApi_HostAddress}}/api/enrollments
Accept: application/json
X-Training-User : {{TmsApi_BearerToken}}

###

GET {{TmsApi_HostAddress}}/api/assessments/results/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results/
Accept: application/json 
Authorization: Bearer {{TmsApi_BearerToken}}

### 

Get {{TmsApi_HostAddress}}/api/enrollments/worker-smoke
Accept: application/json